# Site settings
title: _complete
header-img: img/sandback2.jpg
email: info@complexrefined.com
copyright_name: ComplexRefined Ltd
description: "A place where ComplexRefined shares about learnings and ways to get in touch!"
baseurl: ""
url: "https://complexrefined.com"
twitter_username: ComplexRefined
github_username: ComplexRefined
facebook_username: ComplexRefined
email_username: info@complexrefined.com
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
